services:
  times-receiver:
    build:
      context: .
      dockerfile: Dockerfile
    image: renaneunao/saas-cartola-associar-time-gateway:latest
    container_name: cartola-aero-times-receiver-container
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "5001"
    networks:
      infra_network:
        aliases:
          - cartola-aero-associar-gateway
          - times-receiver
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"

networks:
  infra_network:
    external: true
